### ISSUE TITLE
Ability to use as a library

### ISSUE THREAD

**Issue by derekperkins** [kloeckner-i/db-auth-gateway#4]
As currently written, all the logic lives inside `/internal`, which makes sense to limit your api exposure. How do you feel about potentially making at least some portion public for use as a library? I'm currently investigating the feasibility in the Vitess project. https://github.com/vitessio/vitess/issues/8103

**Comment by dpeckett** [comment]
Hi Derek,

Thank you for your interest however this is a feature we intentionally do not support (as it would limit our flexibility). I'd recommend taking a look at the cloudsql-proxy which explicitly supports library use. 

Given that, there's definitely an open niche out there for a lightweight Cloud SQL authentication library. Perhaps even a fork of this project.
